name: genauth
description: "GenAuth - TOTP/2FA Authenticator"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  genotp_flutter: ^0.0.2
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.2.0
  local_auth: ^3.0.1
  flutter_secure_storage: ^10.3.1
  intl: ^0.20.2
  flutter_slidable: ^4.0.3
  flutter_localization: ^0.4.0
  url_launcher: ^6.3.1
  flutter_svg: ^2.1.0
  cryptography: ^2.7.0
  share_plus: ^10.1.4
  file_picker: ^8.1.2
  path_provider: ^2.1.5
  otpauth_migration: ^0.0.7
  fixnum: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/logos/logo.png
  min_sdk_android: 21
  adaptive_icon_foreground: assets/logos/logo_no_bg.png
  adaptive_icon_background: "#0F172A"
  web:
    generate: true
    image_path: assets/logos/logo.png
    background_color: "#0F172A"
    theme_color: "#0F172A"
  windows:
    generate: true
    image_path: assets/logos/logo.png
    icon_size: 48
  macos:
    generate: true
    image_path: assets/logos/logo.png

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/logos/logo.png
    - assets/logos/logo_no_bg.png
    - assets/logos/generated/
    - assets/icons/
